### PR TITLE
J'ajoute la template sur master

### PR DESCRIPTION
**Pull request by EdenComp**
# Description

Lorem ipsum

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

There is no breaking changes

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the needed labels
- [ ] I have linked this PR to an issue
- [ ] I have linked this PR to a milestone
- [ ] I have linked this PR to a project
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

What is that repo what am i doing

### CODE REVIEW

**Comment by RezaRahemtola** [comment]
d ja fé mek

**Comment by EdenComp** [comment]
ba non ces pa merj

**Comment by RezaRahemtola** [comment]
> ba non ces pa merj

ba si #6

**Comment by EdenComp** [comment]
a maille bade jeu vais la cloz ah nouvo alor

**Pull request closed without merging**
